<?php

declare(strict_types=1);

namespace Momo\Discovery;

/**
 * Patches vendor/composer/autoload_psr4.php by merging
 * local module namespaces into the existing Composer autoload map.
 *
 * Strategy:
 * - Read existing autoload_psr4.php via require (safe, returns array)
 * - Merge local module additions (local wins on conflict)
 * - Write back using var_export — guaranteed valid PHP syntax
 * - Replace absolute paths with $baseDir/$vendorDir expressions
 *   so the file remains portable across environments
 *
 * We intentionally do NOT patch autoload_static.php — regex-patching
 * a generated PHP class is fragile and caused parse errors in the past.
 * The file-based PSR-4 loader (autoload_psr4.php) is always active
 * unless --optimize or --classmap-authoritative flags are used.
 */
final readonly class AutoloadPatcher
{
    public function __construct(
        private string $vendorDir,
    ) {}

    /**
     * @param array<string, list<string>> $additions
     */
    public function patch(array $additions): void
    {
        $psr4File = $this->vendorDir . '/composer/autoload_psr4.php';
        $existing = $this->readExisting($psr4File);
        $merged   = array_merge($existing, $additions);

        $this->write($psr4File, $merged);
    }

    /**
     * @return array<string, list<string>>
     */
    private function readExisting(string $psr4File): array
    {
        if (!file_exists($psr4File)) {
            return [];
        }

        $result = require $psr4File;

        if (!is_array($result)) {
            return [];
        }

        $validated = [];

        foreach ($result as $namespace => $paths) {
            if (!is_string($namespace)) {
                continue;
            }

            if (!is_array($paths)) {
                continue;
            }

            /** @var list<string> $stringPaths */
            $stringPaths = array_values(array_filter($paths, is_string(...)));
            $validated[$namespace] = $stringPaths;
        }

        return $validated;
    }

    /**
     * @param array<string, list<string>> $merged
     */
    private function write(string $psr4File, array $merged): void
    {
        $vendorDir = $this->vendorDir;
        $baseDir   = dirname($vendorDir);

        $export = var_export($merged, true);

        $export = str_replace(
            var_export($vendorDir, true),
            '$vendorDir',
            $export,
        );

        $export = str_replace(
            var_export($baseDir . '/', true),
            "\$baseDir . '/",
            $export,
        );

        $export = str_replace(
            var_export($baseDir, true),
            '$baseDir',
            $export,
        );

        $content = <<<PHP
            <?php

            // autoload_psr4.php @generated by Composer + momo-framework/discovery
            // Do not edit — regenerated on every composer dump-autoload

            \$vendorDir = dirname(__DIR__);
            \$baseDir   = dirname(\$vendorDir);

            return {$export};
            PHP;

        file_put_contents($psr4File, $content);
    }
}
