<?php

declare(strict_types=1);

namespace Momo\Discovery;

/**
 * AutoloadPatcher
 *
 * Injects local module namespaces into the Composer-generated PSR-4 map.
 *
 * Strategy:
 *   1. autoload_psr4.php  — rewritten from scratch with merged data (safe, we own the format).
 *   2. autoload_static.php — regenerated programmatically from the merged PSR-4 map,
 *      avoiding brittle string-search/replace on Composer's generated code.
 *
 * @internal Core discovery component.
 */
final readonly class AutoloadPatcher
{
    public function __construct(
        private string $vendorDir,
    ) {}

    /**
     * Apply namespace additions to the PSR-4 configuration.
     *
     * @param array<string, list<string>> $additions Map of [Namespace\ => [Paths]]
     */
    public function patch(array $additions): void
    {
        $psr4File   = $this->vendorDir . '/composer/autoload_psr4.php';
        $staticFile = $this->vendorDir . '/composer/autoload_static.php';

        $existing = $this->readExisting($psr4File);
        $merged   = array_merge($existing, $additions);

        $this->writePsr4File($psr4File, $merged);

        if (file_exists($staticFile)) {
            $this->regenerateStaticFile($staticFile, $merged);
        }
    }

    // ── Read ──────────────────────────────────────────────────────────────────

    /**
     * Read and validate the existing PSR-4 map.
     *
     * @return array<string, list<string>>
     */
    private function readExisting(string $psr4File): array
    {
        if (!file_exists($psr4File)) {
            return [];
        }

        $result = require $psr4File;

        if (!is_array($result)) {
            return [];
        }

        $validated = [];

        foreach ($result as $namespace => $paths) {
            if (!is_string($namespace)) {
                continue;
            }

            if (!is_array($paths)) {
                continue;
            }

            $stringPaths = array_values(array_filter($paths, is_string(...)));

            if ($stringPaths !== []) {
                $validated[$namespace] = $stringPaths;
            }
        }

        return $validated;
    }

    // ── Write autoload_psr4.php ───────────────────────────────────────────────

    /**
     * Write the merged PSR-4 map to autoload_psr4.php.
     *
     * Replaces absolute vendor/base dir paths with $vendorDir / $baseDir
     * variables so the file is portable across machines.
     *
     * @param array<string, list<string>> $merged
     */
    private function writePsr4File(string $psr4File, array $merged): void
    {
        $vendorDir = $this->vendorDir;
        $baseDir   = dirname($vendorDir);

        $export = var_export($merged, true);
        $export = str_replace(var_export($vendorDir, true), '$vendorDir', $export);
        $export = str_replace(var_export($baseDir . '/', true), "\$baseDir . '/", $export);
        $export = str_replace(var_export($baseDir, true), '$baseDir', $export);

        $content = <<<PHP
            <?php

            // autoload_psr4.php @generated by Composer + momo-framework/discovery
            // Do not edit — regenerated on every composer dump-autoload

            \$vendorDir = dirname(__DIR__);
            \$baseDir   = dirname(\$vendorDir);

            return {$export};
            PHP;

        file_put_contents($psr4File, $content);
    }

    // ── Regenerate autoload_static.php ────────────────────────────────────────

    /**
     * Regenerate autoload_static.php by reading the existing file's class name
     * and other static maps, then rebuilding the PSR-4 sections from scratch.
     *
     * This avoids all string-search/replace on Composer's generated code.
     * Only the PSR-4 sections are replaced; classmap, files, etc. are preserved
     * verbatim from the original file.
     *
     * @param array<string, list<string>> $merged Complete merged PSR-4 map
     */
    private function regenerateStaticFile(string $staticFile, array $merged): void
    {
        $original = file_get_contents($staticFile);
        if ($original === false) {
            return;
        }

        // Extract the class name Composer generated (e.g. ComposerStaticInit1234abc)
        if (!preg_match('/class\s+(ComposerStaticInit\w+)/', $original, $m)) {
            return;
        }

        $baseDir   = dirname($this->vendorDir);

        // Build prefixLengthsPsr4: grouped by first character
        $prefixLengths = $this->buildPrefixLengths($merged);

        // Build prefixDirsPsr4: namespace => [absolute paths]
        $prefixDirs = $this->buildPrefixDirs($merged, $baseDir);

        // Replace only the two PSR-4 sections in the original file
        $content = $this->replacePsr4Section(
            $original,
            'prefixLengthsPsr4',
            $this->renderPrefixLengths($prefixLengths),
        );

        $content = $this->replacePsr4Section(
            $content,
            'prefixDirsPsr4',
            $this->renderPrefixDirs($prefixDirs),
        );

        file_put_contents($staticFile, $content);
    }

    /**
     * Build the prefix-lengths map grouped by first character.
     *
     * @param  array<string, list<string>> $merged
     * @return array<string, array<string, int>>
     */
    private function buildPrefixLengths(array $merged): array
    {
        $result = [];

        foreach (array_keys($merged) as $namespace) {
            $char = $namespace[0];
            $result[$char][$namespace] = strlen($namespace);
        }

        ksort($result);

        return $result;
    }

    /**
     * Build the prefix-dirs map with paths relative to $baseDir.
     *
     * Paths that live inside $baseDir are expressed as
     * __DIR__ . '/../../relative/path' so the file stays portable.
     * Paths outside $baseDir are kept as absolute strings.
     *
     * @param  array<string, list<string>> $merged
     * @return array<string, list<string>>  namespace => [path expressions]
     */
    private function buildPrefixDirs(array $merged, string $baseDir): array
    {
        $result = [];

        foreach ($merged as $namespace => $paths) {
            $expressions = [];

            foreach ($paths as $path) {
                // vendor/composer is two levels deep from $baseDir
                if (str_starts_with($path, $baseDir . '/')) {
                    $relative     = substr($path, strlen($baseDir) + 1);
                    $expressions[] = "__DIR__ . '/../../" . $relative . "'";
                } else {
                    // Absolute path outside project root — keep as-is
                    $expressions[] = var_export($path, true);
                }
            }

            $result[$namespace] = $expressions;
        }

        return $result;
    }

    /**
     * Render the prefixLengthsPsr4 array body.
     *
     * @param array<string, array<string, int>> $prefixLengths
     */
    private function renderPrefixLengths(array $prefixLengths): string
    {
        $lines = [];

        foreach ($prefixLengths as $char => $entries) {
            $lines[] = sprintf("        '%s' => array(", $char);
            foreach ($entries as $namespace => $length) {
                $escaped = str_replace('\\', '\\\\', $namespace);
                $lines[] = sprintf("            '%s' => %d,", $escaped, $length);
            }

            $lines[] = "        ),";
        }

        return implode("\n", $lines);
    }

    /**
     * Render the prefixDirsPsr4 array body.
     *
     * @param array<string, list<string>> $prefixDirs  namespace => [path expressions]
     */
    private function renderPrefixDirs(array $prefixDirs): string
    {
        $lines = [];

        foreach ($prefixDirs as $namespace => $expressions) {
            $escaped = str_replace('\\', '\\\\', $namespace);
            $lines[] = sprintf("        '%s' => array(", $escaped);
            foreach ($expressions as $i => $expr) {
                $lines[] = sprintf('            %d => %s,', $i, $expr);
            }

            $lines[] = "        ),";
        }

        return implode("\n", $lines);
    }

    /**
     * Replace a single PSR-4 section in the static file content.
     * and replaces the inner content with $replacement.
     */
    private function replacePsr4Section(
        string $content,
        string $propertyName,
        string $replacement,
    ): string {
        $pattern = '/(public\s+static\s+\$' . preg_quote($propertyName, '/') . '\s*=\s*array\s*\()([^;]*?)(\);)/s';

        return preg_replace(
            $pattern,
            '$1' . "\n" . $replacement . "\n    " . '$3',
            $content,
        ) ?? $content;
    }
}
