<?php

declare(strict_types=1);

namespace Momo\Discovery;

/**
 * AutoloadPatcher
 *
 * Injects local module namespaces into the Composer-generated PSR-4 map.
 *
 * @internal Core discovery component.
 */
final readonly class AutoloadPatcher
{
    public function __construct(
        private string $vendorDir,
    ) {}

    /**
     * Apply namespace additions to the PSR-4 configuration.
     *
     * @param array<string, list<string>> $additions Map of [Namespace\ => [Paths]]
     */
    public function patch(array $additions): void
    {
        $psr4File = $this->vendorDir . '/composer/autoload_psr4.php';
        $staticFile = $this->vendorDir . '/composer/autoload_static.php';
        
        $existing = $this->readExisting($psr4File);
        $merged = array_merge($existing, $additions);

        $this->writePsr4File($psr4File, $merged);
        
        if (file_exists($staticFile)) {
            $this->patchStaticFile($staticFile, $additions);
        }
    }

    /**
     * Read the existing PSR-4 map from the Composer file.
     *
     * @param string $psr4File Path to autoload_psr4.php
     * @return array<string, list<string>> Validated PSR-4 map.
     */
    private function readExisting(string $psr4File): array
    {
        if (!file_exists($psr4File)) {
            return [];
        }

        $result = require $psr4File;

        if (!is_array($result)) {
            return [];
        }

        $validated = [];

        foreach ($result as $namespace => $paths) {
            if (!is_string($namespace)) {
                continue;
            }

            if (!is_array($paths)) {
                continue;
            }

            $stringPaths = array_values(array_filter($paths, is_string(...)));
            $validated[$namespace] = $stringPaths;
        }

        return $validated;
    }

    /**
     * Write the merged PSR-4 map to autoload_psr4.php.
     *
     * @param string $psr4File Target file path.
     * @param array<string, list<string>> $merged The complete map to write.
     */
    private function writePsr4File(string $psr4File, array $merged): void
    {
        $vendorDir = $this->vendorDir;
        $baseDir = dirname($vendorDir);

        $export = var_export($merged, true);

        $export = str_replace(
            var_export($vendorDir, true),
            '$vendorDir',
            $export,
        );

        $export = str_replace(
            var_export($baseDir . '/', true),
            "\$baseDir . '/",
            $export,
        );

        $export = str_replace(
            var_export($baseDir, true),
            '$baseDir',
            $export,
        );

        $content = <<<PHP
            <?php

            // autoload_psr4.php @generated by Composer + momo-framework/discovery
            // Do not edit — regenerated on every composer dump-autoload

            \$vendorDir = dirname(__DIR__);
            \$baseDir   = dirname(\$vendorDir);

            return {$export};
            PHP;

        file_put_contents($psr4File, $content);
    }

    /**
     * Patch the optimized autoload_static.php file to include local modules.
     *
     * @param string $staticFile Path to autoload_static.php
     * @param array<string, list<string>> $additions Namespaces to add
     */
    private function patchStaticFile(string $staticFile, array $additions): void
    {
        $content = file_get_contents($staticFile);
        if ($content === false) {
            return;
        }

        $baseDir = dirname($this->vendorDir);

        // Include the file to get current values
        $staticClass = require $staticFile;
        if (!is_object($staticClass)) {
            return;
        }

        $className = $staticClass::class;
        
        // Get current values via reflection
        $lengthsProp = new \ReflectionProperty($className, 'prefixLengthsPsr4');
        $dirsProp = new \ReflectionProperty($className, 'prefixDirsPsr4');
        
        $existingLengths = $lengthsProp->getValue();
        $existingDirs = $dirsProp->getValue();

        // Merge additions
        foreach ($additions as $namespace => $paths) {
            $firstChar = $namespace[0];
            $existingLengths[$firstChar][$namespace] = strlen($namespace);
            
            $absolutePaths = [];
            foreach ($paths as $path) {
                $absolutePaths[] = str_replace($baseDir . '/', '__DIR__ . \'/..\' . \'/', $path) . '\'';
            }
            $existingDirs[$firstChar][$namespace] = $absolutePaths;
        }

        // Regenerate the arrays
        $lengthsExport = $this->exportArray($existingLengths);
        $dirsExport = $this->exportArray($existingDirs);

        // Replace in content
        $content = preg_replace(
            '/public static \$prefixLengthsPsr4 = array \([^;]+\);/s',
            'public static $prefixLengthsPsr4 = ' . $lengthsExport . ';',
            $content
        );

        $content = preg_replace(
            '/public static \$prefixDirsPsr4 = array \([^;]+\);/s',
            'public static $prefixDirsPsr4 = ' . $dirsExport . ';',
            $content
        );

        file_put_contents($staticFile, $content);
    }

    /**
     * Export an array in the same format as Composer's static file.
     *
     * @param array<string, mixed> $array
     * @return string
     */
    private function exportArray(array $array): string
    {
        $export = var_export($array, true);
        return "array ($export)";
    }
}
