<?php

/**
 * This file is part of Momo Framework.
 *
 * @copyright Vahe Sargsyan
 * @license   AGPL-3.0-or-later <https://www.gnu.org/licenses/agpl-3.0.html>
 * @link      https://github.com/momo-framework
 */

declare(strict_types=1);

namespace Momo\Discovery;

use RuntimeException;

final readonly class ModuleAutoloadWriter
{
    public function __construct(
        private string $rootDir,
    ) {}

    /**
     * @param array<string, list<string>> $additions
     */
    public function write(string $cacheFile, array $additions): void
    {
        $cacheDir = dirname($cacheFile);

        if (!is_dir($cacheDir) && !@mkdir($cacheDir, 0755, true) && !is_dir($cacheDir)) {
            throw new RuntimeException(sprintf('Directory "%s" could not be created.', $cacheDir));
        }

        $lines   = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = '// modules-autoload.php @generated by momo-framework/discovery';
        $lines[] = '// Do not edit — regenerated on every composer dump-autoload';
        $lines[] = '';
        $lines[] = '/** @var \Composer\Autoload\ClassLoader $loader */';
        $lines[] = '';

        foreach ($additions as $namespace => $paths) {
            $pathExprs = [];

            foreach ($paths as $path) {
                if (str_starts_with((string) $path, $this->rootDir . '/')) {
                    $relative    = substr((string) $path, strlen($this->rootDir) + 1);
                    $pathExprs[] = "__DIR__ . '/../../" . $relative . "'";
                } else {
                    $pathExprs[] = var_export($path, true);
                }
            }

            $lines[] = sprintf(
                "\$loader->addPsr4(%s, [%s]);",
                var_export($namespace, true),
                implode(', ', $pathExprs),
            );
        }

        $lines[] = '';

        $result = @file_put_contents($cacheFile, implode("\n", $lines));

        if ($result === false) {
            throw new RuntimeException(sprintf('Failed to write module autoload cache to "%s".', $cacheFile));
        }
    }
}
