<?php

declare(strict_types=1);

namespace Momo\Discovery;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\Event;
use Composer\Script\ScriptEvents;
use DirectoryIterator;

final class MomoPlugin implements PluginInterface, EventSubscriberInterface
{
    public function activate(Composer $composer, IOInterface $io): void {}
    public function deactivate(Composer $composer, IOInterface $io): void {}
    public function uninstall(Composer $composer, IOInterface $io): void {}

    public static function getSubscribedEvents(): array
    {
        return [ScriptEvents::POST_AUTOLOAD_DUMP => 'onPostAutoloadDump'];
    }

    public function onPostAutoloadDump(Event $event): void
    {
        $composer   = $event->getComposer();
        $vendorDir  = rtrim((string) $composer->getConfig()->get('vendor-dir'), '/');
        $rootDir    = dirname($vendorDir);

        $additions = $this->scanModules($rootDir);

        if ($additions === []) {
            $event->getIO()->write('<info>momo-discovery:</info> no local modules found.');
            return;
        }

        $this->patchPsr4File($vendorDir, $additions);
        $this->ensureFileLoader($vendorDir);

        $event->getIO()->write(
            '<info>momo-discovery:</info> injected ' . count($additions) . ' local module namespace(s).'
        );
    }

    /**
     * @return array<string, list<string>>
     */
    private function scanModules(string $rootDir): array
    {
        $additions  = [];
        $modulesDir = $rootDir . '/modules';

        if (!is_dir($modulesDir)) {
            return [];
        }

        foreach (new DirectoryIterator($modulesDir) as $entry) {
            if ($entry->isDot() || !$entry->isDir()) {
                continue;
            }

            $composerJson = $entry->getPathname() . '/composer.json';
            if (!file_exists($composerJson)) {
                continue;
            }

            $data = json_decode((string) file_get_contents($composerJson), true);

            foreach ($data['autoload']['psr-4'] ?? [] as $ns => $relPath) {
                $absPath = $entry->getPathname() . '/' . rtrim($relPath, '/');
                $additions[$ns] = [$absPath];
            }
        }

        return $additions;
    }

    private function patchPsr4File(string $vendorDir, array $additions): void
    {
        $psr4File = $vendorDir . '/composer/autoload_psr4.php';

        $existing = [];
        if (file_exists($psr4File)) {
            $existing = (array) require $psr4File;
        }

        $merged = array_merge($existing, $additions);

        $export = var_export($merged, true);

        file_put_contents(
            $psr4File,
            "<?php\n\n// autoload_psr4.php @generated by Composer + momo-framework/discovery\n\n\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\nreturn " . $this->replaceAbsPathsWithExpressions($export, $vendorDir) . ";\n"
        );
    }

    private function replaceAbsPathsWithExpressions(string $export, string $vendorDir): string
    {
        $baseDir = dirname($vendorDir);

        $export = str_replace(
            var_export($vendorDir, true),
            '$vendorDir',
            $export
        );

        $export = str_replace(
            var_export($baseDir . '/', true),
            '$baseDir . \'/',
            $export
        );

        return str_replace(
            var_export($baseDir, true),
            '$baseDir',
            $export
        );
    }

    private function ensureFileLoader(string $vendorDir): void
    {
        $autoloadFile = $vendorDir . '/autoload.php';
        if (!file_exists($autoloadFile)) {
            return;
        }

        $content = (string) file_get_contents($autoloadFile);
    }
}