name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, pcov
          coverage: pcov

      - name: Install Dependencies
        run: |
          # Учитываем, что пакеты зависят друг от друга
          composer install --prefer-dist --no-progress

      - name: CI
        run: composer ci